name: "Environments from repo"
description: "Get environments from repo"
inputs:
  exclude-envs:
    description: "Environment to exclude"
    required: false
  has-protection-rule:
    description: "Identify only envs with protection rule: default value is true"
    required: false
  repo-token:
    description: "Token for github authentication"
    required: true
  
runs:
  using: "node16"
  main: "dist/index.js"