name: "Deploy App Zendesk"
description: "Adds pull request file changes as a comment to a newly opened PR"
inputs:
  exclude-envs:
    description: "Environment to exclude"
    required: false
  has-protection-rule:
    description: "Identify only envs with protection rule"
    required: false
  repo-token:
    description: "Token for github authentication"
    required: true
  
runs:
  using: "node16"
  main: "dist/index.js"